name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Gradle
        run: ./gradlew clean build

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Install Render CLI
        run: npm install -g render-cli

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services deploy --name UrlShortnerService